# Generated by Django 5.0.1 on 2024-03-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emails',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwords',
        ),
    ]
